import type { SchemaDiff } from "./diff.js";
import type { DatabaseSchema } from "./schema.js";

function columnDefinitionSql(dataType: string, isNullable: boolean, defaultValue: string | null): string {
  const parts = [dataType];
  if (!isNullable) parts.push("NOT NULL");
  if (defaultValue !== null) parts.push(`DEFAULT ${defaultValue}`);
  return parts.join(" ");
}

export function suggestMigration(diff: SchemaDiff, source: DatabaseSchema): string {
  const statements: string[] = [];

  for (const tableName of diff.removedTables) {
    statements.push(`-- Table "${tableName}" exists in source but not in target.`);
    statements.push(`-- CREATE TABLE "${tableName}" (...); -- fill in from source schema`);
  }

  for (const tableName of diff.addedTables) {
    statements.push(`-- Table "${tableName}" exists in target but not in source.`);
    statements.push(`DROP TABLE IF EXISTS "${tableName}"; -- review before running: destructive`);
  }

  for (const tableDiff of diff.changedTables) {
    for (const colDiff of tableDiff.columnDiffs) {
      if (colDiff.kind === "added" && colDiff.after) {
        statements.push(
          `ALTER TABLE "${tableDiff.name}" ADD COLUMN "${colDiff.name}" ${columnDefinitionSql(
            colDiff.after.dataType,
            colDiff.after.isNullable,
            colDiff.after.defaultValue
          )};`
        );
      } else if (colDiff.kind === "removed" && colDiff.before) {
        statements.push(
          `-- Column "${colDiff.name}" missing from target, present in source.\n` +
            `ALTER TABLE "${tableDiff.name}" ADD COLUMN "${colDiff.name}" ${columnDefinitionSql(
              colDiff.before.dataType,
              colDiff.before.isNullable,
              colDiff.before.defaultValue
            )};`
        );
      } else if (colDiff.kind === "changed" && colDiff.before && colDiff.after) {
        if (colDiff.before.dataType !== colDiff.after.dataType) {
          statements.push(
            `ALTER TABLE "${tableDiff.name}" ALTER COLUMN "${colDiff.name}" TYPE ${colDiff.before.dataType} USING "${colDiff.name}"::${colDiff.before.dataType}; -- target had ${colDiff.after.dataType}`
          );
        }
        if (colDiff.before.isNullable !== colDiff.after.isNullable) {
          statements.push(
            `ALTER TABLE "${tableDiff.name}" ALTER COLUMN "${colDiff.name}" ${
              colDiff.before.isNullable ? "DROP NOT NULL" : "SET NOT NULL"
            };`
          );
        }
      }
    }

    for (const indexName of tableDiff.removedIndexes) {
      const idx = source.tables.get(tableDiff.name)?.indexes.find((i) => i.name === indexName);
      if (idx) statements.push(`${idx.definition};`);
    }

    for (const indexName of tableDiff.addedIndexes) {
      statements.push(`DROP INDEX IF EXISTS "${indexName}"; -- review before running: destructive`);
    }
  }

  if (statements.length === 0) {
    return "-- No schema drift detected. No migration needed.";
  }

  return [
    "-- Suggested migration to bring target in line with source schema.",
    "-- Generated by db-diff. Review carefully before applying, especially destructive statements.",
    "",
    ...statements,
  ].join("\n");
}
